/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PictureDisplayPanel.java
 *
 * Created on Mar 13, 2011, 10:59:32 PM
 */



/**
 *
 * @author Wyuh
 */
package dreamlivingroom;

import ClipsInteraction.Answer;
import ClipsInteraction.ClipsEngine;
import ClipsInteraction.Question;
import java.awt.Graphics2D;
import java.awt.Dimension;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;

public class PictureDisplayPanel extends javax.swing.JPanel {

    /** Creates new form PictureDisplayPanel */
    Question currentQuestion;
    ClipsEngine clips;
    MainFrame container;
    private String imagedir = "database/";
    BufferedImage img1,img2;
    BufferedImage sm1,sm2;
    ImageIcon ic1,ic2;

   

    /** Creates new form QuestionPanel */
    public PictureDisplayPanel(MainFrame mainFrame) {
        container = mainFrame;
        this.clips = container.getClips();
        currentQuestion = null;
        initComponents();

    }

    public void setQuestion(Question question) throws IOException{
        String s1,s2,s3,s4;
        //Assign question, question looks the same for each function
        currentQuestion = question;

        //Display question
        jLabel1.setText(question.getText());

        //Display valid answers for each group of furniture
        s1 = question.getValidAnswers().get(0);
        s2 = question.getValidAnswers().get(1);

       
        s3 = "database/" + s1 + ".jpg";
        s4 = "database/" + s2 + ".jpg";
        URL u1 = this.getClass().getResource(s3);
        URL u2 = this.getClass().getResource(s4);
        //File file1 = new File(s3);
        //File file2 = new File(s4);

        img1 = ImageIO.read(u1);
        img2 = ImageIO.read(u2);

        sm1 = new BufferedImage(248,248,BufferedImage.TYPE_INT_RGB);
        sm2 = new BufferedImage(248,248,BufferedImage.TYPE_INT_RGB);
        Graphics2D g1 = sm1.createGraphics();
        Graphics2D g2 = sm2.createGraphics();
        g1.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_SPEED);
        g1.drawImage(img1,0,0,250,250,null);
        g1.dispose();
        g2.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_SPEED);
        g2.drawImage(img2,0,0,250,250,null);
        g2.dispose();
        ic1 = new ImageIcon(sm1);
        ic2 = new ImageIcon(sm2);
        jButton1.setIcon(ic1);
        jButton2.setIcon(ic2);
        jButton1.setActionCommand(s1);
        jButton2.setActionCommand(s2);

        repaint();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("jButton1");
        jButton1.setMaximumSize(new java.awt.Dimension(248, 248));
        jButton1.setMinimumSize(new java.awt.Dimension(248, 248));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("jButton2");
        jButton2.setMaximumSize(new java.awt.Dimension(248, 248));
        jButton2.setMinimumSize(new java.awt.Dimension(248, 248));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (currentQuestion != null){
            String sValue = "";
            sValue = jButton1.getActionCommand();
            Answer answer = new Answer(currentQuestion.getQuestionId(),currentQuestion.getQuestionId(), sValue);
            clips.setAnswer(answer);
            try {
                container.RunClips();
            } catch (IOException ex) {
                Logger.getLogger(PictureDisplayPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (currentQuestion != null){
            String sValue = "";
            sValue = jButton2.getActionCommand();
            Answer answer = new Answer(currentQuestion.getQuestionId(),currentQuestion.getQuestionId(), sValue);
            clips.setAnswer(answer);
            try {
                container.RunClips();
            } catch (IOException ex) {
                Logger.getLogger(PictureDisplayPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
