/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PictureDisplayPanel.java
 *
 * Created on Mar 13, 2011, 10:59:32 PM
 */



/**
 *
 * @author Wyuh
 */
package dreamlivingroom;

import ClipsInteraction.Answer;
import ClipsInteraction.ClipsEngine;
import ClipsInteraction.Question;
import javax.swing.*;

public class PictureDisplayPanel extends javax.swing.JPanel {

    /** Creates new form PictureDisplayPanel */
    Question currentQuestion;
    ClipsEngine clips;
    MainFrame container;
    private String imagedir = "database/";

   

    /** Creates new form QuestionPanel */
    public PictureDisplayPanel(MainFrame mainFrame) {
        container = mainFrame;
        this.clips = container.getClips();
        currentQuestion = null;
        initComponents();

    }

    public void setQuestion(Question question){
        String s1,s2;
        //Assign question, question looks the same for each function
        currentQuestion = question;

        //Display question
        jLabel1.setText(question.getText());

        //Display valid answers for each group of furniture
        for( int i = 0; i<2; i++)
        {
             s1 = question.getValidAnswers().get(0);
             s2 = question.getValidAnswers().get(1);
             s1 = s1 + ".jpg";
             s2 = s2 + ".jpg";
             jButton1 = new JButton(new ImageIcon(imagedir + s1));
             jButton2 = new JButton(new ImageIcon(imagedir + s2));
             repaint();

        }
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel1)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (currentQuestion != null){
            String sValue = "";
            if(currentQuestion.getQuestionType().equals("furniture-preference"))
            {
              sValue = jButton1.getActionCommand();
            }
            Answer answer = new Answer(currentQuestion.getQuestionId(),currentQuestion.getQuestionId(), sValue);
            clips.setAnswer(answer);
            container.RunClips();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (currentQuestion != null){
            String sValue = "";
            if(currentQuestion.getQuestionType().equals("furniture-preference"))
            {
              sValue = jButton2.getActionCommand();
            }
            Answer answer = new Answer(currentQuestion.getQuestionId(),currentQuestion.getQuestionId(), sValue);
            clips.setAnswer(answer);
            container.RunClips();
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
