/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuestionFrame.java
 *
 * Created on Feb 27, 2011, 9:01:52 PM
 */

package dreamlivingroom;

import ClipsInteraction.ClipsEngine;
import ClipsInteraction.Question;

/**
 *
 * @author Standard
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form QuestionFrame */
    public MainFrame() {
        initComponents();
        initQuestionPanel();
        runClips();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    private void initQuestionPanel()
    {
        mainPanel = new QuestionPanel();
        mainPanel.setSize(300,400);
        add(mainPanel);
    }

    private void runClips()
    {
        ClipsEngine clips = new ClipsEngine("CS4244.clp");
        clips.runEnvironment();
        Question question = clips.getQuestion();
        ((QuestionPanel)mainPanel).setQuestion(question);
    }

    private javax.swing.JPanel mainPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
