/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QuestionPanel.java
 *
 * Created on Feb 27, 2011, 9:57:44 PM
 */

package dreamlivingroom;

import ClipsInteraction.Answer;
import ClipsInteraction.ClipsEngine;
import ClipsInteraction.Question;
import javax.swing.JRadioButton;

/**
 *
 * @author Standard
 */
public class QuestionPanel extends javax.swing.JPanel {

    Question currentQuestion;
    ClipsEngine clips;
    MainFrame container;

    /** Creates new form QuestionPanel */
    public QuestionPanel(MainFrame mainFrame) {
        container = mainFrame;
        this.clips = container.getClips();
        initComponents();
        currentQuestion = null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("Submit");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(180, 180, 180)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((currentQuestion != null) && (buttonGroup1.getSelection() != null))
        {
            Answer answer = new Answer(currentQuestion.getQuestionId(),
                    currentQuestion.getQuestionType(),
                    buttonGroup1.getSelection().getActionCommand());
            clips.setAnswer(answer);
            container.RunClips();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setQuestion(Question question)
    {
        // Assign question
        currentQuestion = question;
        
        // Display question
        jLabel1.setText(question.getText());

        // Display valid answers
        for (int i=0; i<question.getValidAnswers().size(); i++)
        {
            System.out.println(question.getValidAnswers().get(i));
            JRadioButton button =
                    new JRadioButton(question.getValidAnswers().get(i),false);
            button.setActionCommand(question.getValidAnswers().get(i));
            button.setSize(200,20);
            button.setLocation(50, 50+25*i);
            button.setVisible(true);
            buttonGroup1.add(button);
            add(button);
            repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
