/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WindowDoorPanel.java
 *
 * Created on Feb 28, 2011, 5:35:19 PM
 */

package dreamlivingroom;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author caofan
 */
public class WindowDoorPanel extends javax.swing.JPanel {

    private Image windowImage;
    private Image doorImage;
    int windowX=10, windowY=100, doorX=10, doorY=150;
    int mouseX, mouseY;
    char selected;
    int roomLength, roomWidth;

    /** Creates new form WindowDoorPanel */
    public WindowDoorPanel(MainFrame frame) {
        roomLength = frame.getRoomLength();
        roomWidth = frame.getRoomWidth();
        initComponents();
        textLabel.setText("Please drag the window and door to proper positions.");
        try{
            windowImage = ImageIO.read(new File("window.jpg"));
            doorImage = ImageIO.read(new File("door.jpg"));
        } catch(IOException ex) {
            System.out.println("Unable to fetch image");
            System.exit(0);
        }
        
        MediaTracker mt = new MediaTracker(this);
        mt.addImage(windowImage,1);
        mt.addImage(doorImage,1);
        try {
            mt.waitForAll();
        } catch(Exception e) {
            System.out.println("Exception while loading image.");
            System.exit(0);
        }
        addMouseListener(new MyMouseListener());
        addMouseMotionListener(new MyMouseMotionListener());
    }
    
    class MyMouseListener extends MouseAdapter {
        public void mousePressed(MouseEvent e) {
            mouseX = e.getX();
            mouseY = e.getY();
            if(within(windowX,windowY,40,40,mouseX,mouseY))
                selected='w';
            else if(within(doorX,doorY,40,40,mouseX,mouseY))
                selected='d';
            else
                selected=0;
        }
    }
    
    boolean within (int x, int y, int length, int width, int currX, int currY) {
        return x<=currX&&y<=currY&&currX<=x+length&&currY<y+width;
    }
    class MyMouseMotionListener extends MouseMotionAdapter {
        @Override
        public void mouseDragged(MouseEvent e) {
            int tempX = e.getX();
            int tempY = e.getY();
            if(selected=='w'){
                windowX = windowX +tempX-mouseX;
                windowY = windowY + tempY-mouseY;
            }
            else if(selected=='d') {
                doorX = doorX+tempX-mouseX;
                doorY = doorY+tempY-mouseY;
            }
            mouseX = tempX;
            mouseY = tempY;
            repaint();
        }
        
        
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        int plotableLength = this.getWidth() - 70;
        int plotableWidth = this.getHeight() - 70;
        System.out.println(plotableLength+" "+plotableWidth);
        System.out.println(roomLength +" " + roomWidth);
        double ratio = Math.max((double)roomLength/plotableLength, (double)roomWidth/plotableWidth);
        System.out.println(ratio);
        int plotLength = (int) (roomLength/ratio);
        int plotWidth = (int) (roomWidth/ratio);
        System.out.println(plotLength + " " + plotWidth);
        g.drawRect(60,60,plotLength,plotWidth);
        
        g.drawImage(windowImage, windowX,windowY,40,40, this);
        g.drawImage(doorImage, doorX, doorY,40,40, this);
        
    }
    

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();

        textLabel.setText("jLabel1");
        textLabel.setName("textLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLabel)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textLabel)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables

}
